# Generated by Django 5.2.17 on 2026-09-03 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('payments', '0001_initial'),
        ('requests', '0002_collectionrequest_laboratory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.CharField(choices=[('pharmacy', 'Farmácia'), ('technician', 'Técnico'), ('reseller', 'Revendedor')], max_length=16)),
                ('beneficiary_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='beneficiário específico (opcional)')),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'Percentual'), ('FIXED', 'Valor fixo')], max_length=16)),
                ('value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('trigger', models.CharField(choices=[('PAYMENT_CONFIRMED', 'Confirmação do pagamento'), ('COLLECTION_COMPLETED', 'Coleta concluída')], max_length=32)),
                ('valid_from', models.DateField(blank=True, null=True, verbose_name='válida de')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='válida até')),
                ('active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_commission_rules', to=settings.AUTH_USER_MODEL)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commission_rules', to='organizations.laboratory', verbose_name='laboratório')),
            ],
            options={
                'verbose_name': 'regra de comissão',
                'verbose_name_plural': 'regras de comissão',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('beneficiary_type', models.CharField(choices=[('pharmacy', 'Farmácia'), ('technician', 'Técnico'), ('reseller', 'Revendedor')], max_length=16)),
                ('beneficiary_id', models.PositiveIntegerField(verbose_name='id do beneficiário')),
                ('calculation_type', models.CharField(choices=[('PERCENTAGE', 'Percentual'), ('FIXED', 'Valor fixo')], max_length=16)),
                ('rule_value', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor da regra')),
                ('trigger', models.CharField(choices=[('PAYMENT_CONFIRMED', 'Confirmação do pagamento'), ('COLLECTION_COMPLETED', 'Coleta concluída')], max_length=32)),
                ('base_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='base de cálculo')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('status', models.CharField(choices=[('GENERATED', 'Gerada'), ('PAID', 'Paga'), ('REVERSED', 'Estornada')], db_index=True, default='GENERATED', max_length=16, verbose_name='status')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paga em')),
                ('reversed_at', models.DateTimeField(blank=True, null=True, verbose_name='estornada em')),
                ('reversed_reason', models.CharField(blank=True, max_length=255, verbose_name='motivo do estorno')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions', to='payments.payment', verbose_name='pagamento de origem')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='requests.collectionrequest', verbose_name='solicitação')),
                ('rule', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ledger', to='commissions.commissionrule', verbose_name='regra')),
            ],
            options={
                'verbose_name': 'comissão',
                'verbose_name_plural': 'comissões',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('request', 'beneficiary_type', 'beneficiary_id', 'rule'), name='unique_commission_per_rule_beneficiary')],
            },
        ),
    ]
