# Generated by Django 5.2.17 on 2026-09-03 20:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='telefone')),
                ('provider', models.CharField(default='simulator', max_length=24, verbose_name='provedor')),
                ('status', models.CharField(choices=[('open', 'Aberta'), ('human', 'Encaminhada a humano'), ('closed', 'Encerrada')], default='open', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='organizations.laboratory', verbose_name='canal do laboratório')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_conversations', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'conversa WhatsApp',
                'verbose_name_plural': 'conversas WhatsApp',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='WhatsAppMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_message_id', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='id no provedor')),
                ('direction', models.CharField(choices=[('inbound', 'Recebida'), ('outbound', 'Enviada')], max_length=16)),
                ('content', models.TextField(verbose_name='conteúdo')),
                ('ai_interpretation', models.JSONField(blank=True, null=True, verbose_name='interpretação da IA')),
                ('ai_model', models.CharField(blank=True, max_length=64, verbose_name='modelo IA')),
                ('ai_used_mock', models.BooleanField(default=False, verbose_name='usou IA simulada')),
                ('ai_error', models.BooleanField(default=False, verbose_name='erro na IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='whatsapp.whatsappconversation', verbose_name='conversa')),
            ],
            options={
                'verbose_name': 'mensagem WhatsApp',
                'verbose_name_plural': 'mensagens WhatsApp',
                'ordering': ['created_at'],
            },
        ),
    ]
