# Generated by Django 5.2.17 on 2026-09-04 11:32

import apps.whatsapp.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_laboratory_locator_fields'),
        ('technicians', '0001_initial'),
        ('whatsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=20, unique=True, verbose_name='número WhatsApp')),
                ('name', models.CharField(blank=True, max_length=120, verbose_name='nome de exibição')),
                ('meta_bsuid', models.CharField(blank=True, help_text='Handle da Meta, ex.: "@nome.usuario".', max_length=120, validators=[apps.whatsapp.validators.validate_meta_bsuid], verbose_name='BSUID (Meta)')),
                ('is_main', models.BooleanField(default=False, verbose_name='principal')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='organizations.laboratory', verbose_name='laboratório')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='organizations.pharmacy', verbose_name='farmácia')),
                ('reseller', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='organizations.reseller', verbose_name='revenda')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_contacts', to='technicians.technician', verbose_name='técnico')),
            ],
            options={
                'verbose_name': 'contato WhatsApp',
                'verbose_name_plural': 'contatos WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
    ]
