# Generated by Django 5.2.17 on 2026-09-04 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
        ('organizations', '0004_remove_laboratory_address_remove_laboratory_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='laboratory',
            field=models.ForeignKey(blank=True, help_text='Escopo do evento (v1.1.9): permite auditoria por laboratório.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='organizations.laboratory', verbose_name='laboratório'),
        ),
    ]
