# Generated by Django 5.2.17 on 2026-09-03 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True, verbose_name='código')),
                ('name', models.CharField(max_length=160, verbose_name='nome')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'exame',
                'verbose_name_plural': 'exames',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='ExamPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='preço')),
                ('active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='catalog.exam', verbose_name='exame')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_prices', to='organizations.laboratory', verbose_name='laboratório')),
            ],
            options={
                'verbose_name': 'preço de exame',
                'verbose_name_plural': 'preços de exames',
                'ordering': ['exam__code'],
                'constraints': [models.UniqueConstraint(fields=('laboratory', 'exam'), name='unique_price_per_lab_exam')],
            },
        ),
    ]
