# Generated by Django 5.2.17 on 2026-09-03 14:44

import apps.requests.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(default=apps.requests.models._protocol, editable=False, max_length=20, unique=True, verbose_name='protocolo')),
                ('desired_date', models.DateField(blank=True, null=True, verbose_name='data desejada')),
                ('desired_period', models.CharField(blank=True, choices=[('morning', 'Manhã'), ('afternoon', 'Tarde'), ('evening', 'Noite')], max_length=16, verbose_name='período desejado')),
                ('collection_mode', models.CharField(choices=[('pharmacy', 'Farmácia / ponto de coleta'), ('domiciliary', 'Coleta domiciliar'), ('laboratory', 'Laboratório / unidade')], default='pharmacy', max_length=16, verbose_name='modalidade')),
                ('preferred_location', models.CharField(blank=True, max_length=255, verbose_name='local preferido')),
                ('status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('QUOTE_DRAFT', 'Rascunho do orçamento'), ('WAITING_HUMAN_VALIDATION', 'Validação humana'), ('QUOTE_SENT', 'Orçamento final enviado'), ('APPROVED', 'Aprovado'), ('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em realização'), ('COMPLETED', 'Realizado'), ('PAYMENT_PENDING', 'Pagamento pendente'), ('PAYMENT_CONFIRMED', 'Pagamento confirmado'), ('COMMISSION_PENDING', 'Comissão pendente'), ('COMMISSION_GENERATED', 'Comissão gerada'), ('CANCELED', 'Cancelado')], db_index=True, default='REQUESTED', max_length=32, verbose_name='status')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'solicitação de coleta',
                'verbose_name_plural': 'solicitações de coleta',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.requests.models.medical_order_upload_path, verbose_name='arquivo')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='tipo MIME')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_orders', to='requests.collectionrequest', verbose_name='solicitação')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_medical_orders', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'pedido médico',
                'verbose_name_plural': 'pedidos médicos',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='RequestStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('QUOTE_DRAFT', 'Rascunho do orçamento'), ('WAITING_HUMAN_VALIDATION', 'Validação humana'), ('QUOTE_SENT', 'Orçamento final enviado'), ('APPROVED', 'Aprovado'), ('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em realização'), ('COMPLETED', 'Realizado'), ('PAYMENT_PENDING', 'Pagamento pendente'), ('PAYMENT_CONFIRMED', 'Pagamento confirmado'), ('COMMISSION_PENDING', 'Comissão pendente'), ('COMMISSION_GENERATED', 'Comissão gerada'), ('CANCELED', 'Cancelado')], max_length=32, verbose_name='estado anterior')),
                ('to_status', models.CharField(choices=[('REQUESTED', 'Solicitado'), ('QUOTE_DRAFT', 'Rascunho do orçamento'), ('WAITING_HUMAN_VALIDATION', 'Validação humana'), ('QUOTE_SENT', 'Orçamento final enviado'), ('APPROVED', 'Aprovado'), ('SCHEDULED', 'Agendado'), ('IN_PROGRESS', 'Em realização'), ('COMPLETED', 'Realizado'), ('PAYMENT_PENDING', 'Pagamento pendente'), ('PAYMENT_CONFIRMED', 'Pagamento confirmado'), ('COMMISSION_PENDING', 'Comissão pendente'), ('COMMISSION_GENERATED', 'Comissão gerada'), ('CANCELED', 'Cancelado')], max_length=32, verbose_name='estado novo')),
                ('origin', models.CharField(default='system', max_length=32, verbose_name='origem')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='motivo')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadados')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_status_changes', to=settings.AUTH_USER_MODEL, verbose_name='responsável')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='requests.collectionrequest', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'histórico de status',
                'verbose_name_plural': 'históricos de status',
                'ordering': ['created_at'],
            },
        ),
    ]
