# Generated by Django 5.2.17 on 2026-09-04 17:39

import apps.requests.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests', '0002_collectionrequest_laboratory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=apps.requests.models._result_token, editable=False, max_length=48, unique=True, verbose_name='token')),
                ('result_url', models.URLField(blank=True, verbose_name='URL externa do resultado')),
                ('note', models.TextField(blank=True, verbose_name='observação do resultado')),
                ('published', models.BooleanField(default=False, verbose_name='publicado')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='publicado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_exam_results', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_exam_results', to=settings.AUTH_USER_MODEL, verbose_name='publicado por')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_results', to='requests.collectionrequest', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'resultado de exame',
                'verbose_name_plural': 'resultados de exames',
                'ordering': ['-created_at'],
            },
        ),
    ]
