# Generated by Django 5.2.17 on 2026-09-04 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(default='dados_pessoais_servicos', max_length=120, verbose_name='finalidade')),
                ('granted', models.BooleanField(default=True, verbose_name='consentiu')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP')),
                ('user_agent', models.TextField(blank=True, verbose_name='user agent')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='patients.patient', verbose_name='paciente')),
            ],
            options={
                'verbose_name': 'consentimento (LGPD)',
                'verbose_name_plural': 'consentimentos (LGPD)',
                'ordering': ['-created_at'],
            },
        ),
    ]
