# Generated by Django 5.2.17 on 2026-09-04 11:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0003_laboratory_locator_fields'),
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('pharmacy', 'Farmácia'), ('laboratory', 'Laboratório')], max_length=16)),
                ('name', models.CharField(max_length=160, verbose_name='nome do ponto')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('city', models.CharField(blank=True, max_length=80, verbose_name='cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('zip_code', models.CharField(blank=True, max_length=10, verbose_name='CEP')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('is_open', models.BooleanField(default=False, verbose_name='aberto agora')),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], default='active', max_length=16, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_points', to='organizations.laboratory', verbose_name='laboratório da rede')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='collection_points', to='organizations.pharmacy', verbose_name='farmácia anfitriã')),
            ],
            options={
                'verbose_name': 'local de coleta',
                'verbose_name_plural': 'locais de coleta',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CollectionPointSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='aberto em')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='fechado em')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_point_sessions', to='technicians.technician', verbose_name='fechado por')),
                ('opened_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opened_point_sessions', to='technicians.technician', verbose_name='aberto por')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='collection_points.collectionpoint', verbose_name='ponto')),
            ],
            options={
                'verbose_name': 'sessão do ponto de coleta',
                'verbose_name_plural': 'sessões dos pontos de coleta',
                'ordering': ['-open_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningWindow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Segunda'), (1, 'Terça'), (2, 'Quarta'), (3, 'Quinta'), (4, 'Sexta'), (5, 'Sábado'), (6, 'Domingo')], verbose_name='dia')),
                ('open_time', models.TimeField(verbose_name='abre')),
                ('close_time', models.TimeField(verbose_name='fecha')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='windows', to='collection_points.collectionpoint', verbose_name='ponto')),
            ],
            options={
                'verbose_name': 'janela de horário',
                'verbose_name_plural': 'janelas de horário',
                'ordering': ['weekday', 'open_time'],
            },
        ),
        migrations.CreateModel(
            name='TechnicianAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='designação ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_technicians_to_points', to=settings.AUTH_USER_MODEL, verbose_name='designado por')),
                ('point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technician_assignments', to='collection_points.collectionpoint', verbose_name='ponto')),
                ('technician', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collection_point_assignments', to='technicians.technician', verbose_name='técnico')),
            ],
            options={
                'verbose_name': 'designação de técnico',
                'verbose_name_plural': 'designações de técnicos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='collectionpoint',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'pharmacy'), ('pharmacy__isnull', False)), fields=('kind', 'pharmacy'), name='uniq_pharmacy_hosted_point'),
        ),
        migrations.AddConstraint(
            model_name='openingwindow',
            constraint=models.UniqueConstraint(fields=('point', 'weekday', 'open_time', 'close_time'), name='uniq_window_point_day_time'),
        ),
        migrations.AddConstraint(
            model_name='technicianassignment',
            constraint=models.UniqueConstraint(fields=('point', 'technician'), name='uniq_point_technician_assignment'),
        ),
    ]
