# Generated by Django 5.2.17 on 2026-09-03 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveSmallIntegerField(default=1, verbose_name='versão')),
                ('quotation_type', models.CharField(choices=[('draft', 'Rascunho'), ('final', 'Orçamento final')], default='draft', max_length=16, verbose_name='tipo')),
                ('generated_by_ai', models.BooleanField(default=False, verbose_name='gerado por IA')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='total')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validado em')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado em')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='aprovado em')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='recusado em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_quotations', to=settings.AUTH_USER_MODEL, verbose_name='aprovado por')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quotations', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_quotations', to=settings.AUTH_USER_MODEL, verbose_name='recusado por')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='requests.collectionrequest', verbose_name='solicitação')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_quotations', to=settings.AUTH_USER_MODEL, verbose_name='validado por')),
            ],
            options={
                'verbose_name': 'orçamento',
                'verbose_name_plural': 'orçamentos',
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='QuotationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='descrição')),
                ('quantity', models.PositiveSmallIntegerField(default=1, verbose_name='quantidade')),
                ('unit_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='preço unitário')),
                ('source', models.CharField(choices=[('catalog', 'Catálogo do laboratório'), ('manual', 'Entrada manual'), ('ai', 'Extraído por IA')], default='manual', max_length=16, verbose_name='origem')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotation_items', to='catalog.exam', verbose_name='exame')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='quotations.quotation', verbose_name='orçamento')),
            ],
            options={
                'verbose_name': 'item de orçamento',
                'verbose_name_plural': 'itens de orçamento',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='quotation',
            constraint=models.UniqueConstraint(fields=('request', 'version'), name='unique_quote_version_per_request'),
        ),
    ]
