# Generated by Django 5.2.17 on 2026-09-03 20:13

import apps.payments.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests', '0002_collectionrequest_laboratory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.payments.models._code, editable=False, max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='valor')),
                ('method', models.CharField(choices=[('link', 'Link de pagamento'), ('presencial', 'Presencial na coleta')], max_length=16)),
                ('status', models.CharField(choices=[('PENDING', 'Pendente'), ('LINK_CREATED', 'Link criado'), ('AUTHORIZED', 'Autorizado'), ('CONFIRMED', 'Confirmado'), ('FAILED', 'Falhou'), ('REFUNDED', 'Estornado'), ('CANCELED', 'Cancelado')], db_index=True, default='PENDING', max_length=16, verbose_name='status')),
                ('gateway_provider', models.CharField(default='fake', max_length=32, verbose_name='provedor')),
                ('external_reference', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='referência externa')),
                ('payment_url', models.URLField(blank=True, verbose_name='URL de pagamento')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='pago em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_payments', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='requests.collectionrequest', verbose_name='solicitação')),
            ],
            options={
                'verbose_name': 'pagamento',
                'verbose_name_plural': 'pagamentos',
                'ordering': ['-created_at'],
            },
        ),
    ]
