# Generated by Django 5.2.17 on 2026-09-03 20:02

import apps.scheduling.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('requests', '0002_collectionrequest_laboratory'),
        ('technicians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=apps.scheduling.models._code, editable=False, max_length=20, unique=True)),
                ('mode', models.CharField(choices=[('pharmacy', 'Farmácia / ponto de coleta'), ('domiciliary', 'Coleta domiciliar'), ('laboratory', 'Laboratório / unidade')], max_length=16)),
                ('scheduled_at', models.DateTimeField(verbose_name='data e hora agendadas')),
                ('location_label', models.CharField(blank=True, max_length=255, verbose_name='local')),
                ('checkin_at', models.DateTimeField(blank=True, null=True, verbose_name='check-in em')),
                ('checkout_at', models.DateTimeField(blank=True, null=True, verbose_name='check-out em')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='concluída em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_appointments', to=settings.AUTH_USER_MODEL, verbose_name='criado por')),
                ('laboratory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='organizations.laboratory', verbose_name='laboratório')),
                ('pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='organizations.pharmacy', verbose_name='farmácia / ponto')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appointment', to='requests.collectionrequest', verbose_name='solicitação')),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='technicians.technician', verbose_name='técnico')),
            ],
            options={
                'verbose_name': 'agendamento',
                'verbose_name_plural': 'agendamentos',
                'ordering': ['scheduled_at'],
            },
        ),
    ]
