# Generated by Django 5.2.17 on 2026-09-04 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacy',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para cálculo de proximidade (D-01).', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para cálculo de proximidade (D-01).', max_digits=9, null=True, verbose_name='longitude'),
        ),
    ]
