# Generated by Django 5.2.17 on 2026-09-04 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_pharmacy_latitude_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratory',
            name='address',
            field=models.CharField(blank=True, max_length=255, verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='city',
            field=models.CharField(blank=True, max_length=80, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para cálculo de proximidade (D-01).', max_digits=9, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Coordenada para cálculo de proximidade (D-01).', max_digits=9, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='UF'),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='zip_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='CEP'),
        ),
    ]
