# Generated by Django 5.2.17 on 2026-09-04 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_laboratory_locator_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='laboratory',
            name='address',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='city',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='state',
        ),
        migrations.RemoveField(
            model_name='laboratory',
            name='zip_code',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='pharmacy',
            name='longitude',
        ),
    ]
